### ISSUE TITLE
Teleport under Ground

### ISSUE THREAD

**Issue by ChristopherS** [ALitttleBitDifferent/AmbientPrologueBugs#34]
After Teleportation, Astrum appears underground

**Comment by ChristopherS** [comment]
After several tries I am unable to reproduce this issue

**Comment by ChristopherS** [comment]
Looks like it's still a problem after all. Waiting for some info on how to do it (might already be fixed together with #12 though...

**Comment by AjaniBilby** [comment]
The position of a actor is relative to the center of the body, not the feet, so maybe try off-setting the spawn location by the actor's half-height.
(Also unreal is sometimes smart and if it is closer to the top that the bottom of an object when you are inside it it will push you that way).

**Comment by snoopystallion** [comment]
its easy to produce this glitch. 
moved into the ground at a wall: https://youtu.be/9-qvEITejbg?t=3m36s
moved into the ground at the wolf : https://youtu.be/9-qvEITejbg?t=6m
moved into the ground at another wall: https://youtu.be/9-qvEITejbg?t=7m39s

it seems that when you teleport at a spot where something is over you, you will get an offset downwards

**Comment by snoopystallion** [comment]
and just for the lulz. you can teleport under ground even in the active fight against the hunter. making you unable to move at all, sometimes you are lucky and you can jump out. otherwise you have to teleport out of the situation. the worst thing was that this hunter blinded me everytime i got under him. 

and to get under him. aim for his feet when casting the teleport. this will send you right into the ground. but i didnt manage to fall through completely.

**Comment by snoopystallion** [comment]
when you start a new game and run along the right side of the first ruin a bit up the hill so you can see the exit of the first ruin, you can tele port into the ground like shown so often already. but now you are even able to fall through the ground when teleporting. luckily i was able to fly all the way up again to the ground. but when i arrived i suddenly had -63 health and got a shiny game over screen -.-

**Comment by ChristopherS** [comment]
Since most skills are remade, I mark this as closed. If the problem still persists in a later release you can open a new issue.
